-- MySQL Script generated by MySQL Workbench
-- Fri Jan 24 12:46:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banking_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banking_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banking_service` ;
USE `banking_service` ;

-- -----------------------------------------------------
-- Table `banking_service`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`customers` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`customers` (
  `Id` BIGINT NULL,
  `customer_type` ENUM('individual', 'company') NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company_name` VARCHAR(100) NULL DEFAULT NULL,
  `tax_id` VARCHAR(20) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `industry` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`tax_id` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `banking_service`.`customer_representatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`customer_representatives` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`customer_representatives` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `is_primary_contact` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX (`company_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`company_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`branches` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`branches` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `open_date` DATE NOT NULL,
  `employees_employee_id` INT NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `banking_service`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`employees` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`employees` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `branch_id` BIGINT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `job_title` VARCHAR(50) NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `fk_employees_branches1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `banking_service`.`branches` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `banking_service`.`employee_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`employee_roles` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`employee_roles` (
  `Id` INT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NOT NULL,
  `role_name` ENUM('teller', 'loan officer', 'customer support', 'financial advisor', 'manager') NOT NULL,
  `responsibilities` TEXT NULL,
  PRIMARY KEY (`Id`),
  INDEX (`employee_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`accounts` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`accounts` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `account_type` ENUM('savings', 'checking', 'business') NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `opened_date` DATETIME NOT NULL,
  `status` ENUM('active', 'closed', 'suspended') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`Id`),
  INDEX (`customer_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`transactions` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`transactions` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `from_account_id` BIGINT NOT NULL,
  `to_account_id` BIGINT NOT NULL,
  `transaction_type` ENUM('deposit', 'withdrawal', 'transfer', 'payment', 'loan repayment') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('pending', 'completed', 'failed') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`Id`),
  INDEX (`from_account_id` ASC) VISIBLE,
  INDEX (`to_account_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`from_account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE SET NULL,
  CONSTRAINT ``
    FOREIGN KEY (`to_account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE SET NULL);


-- -----------------------------------------------------
-- Table `banking_service`.`loans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`loans` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`loans` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `loan_type` ENUM('personal', 'business', 'mortgage') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `interest_rate` DECIMAL(5,2) NOT NULL,
  `term_months` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `status` ENUM('active', 'closed', 'defaulted') NOT NULL DEFAULT 'active',
  `payment date` DATE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX (`account_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`deposits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`deposits` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`deposits` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `deposit_type` ENUM('fixed', 'recurring') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `interest_rate` DECIMAL(5,2) NOT NULL,
  `term_months` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `maturity_date` DATE NOT NULL,
  `status` ENUM('active', 'closed', 'withdrawn') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`Id`),
  INDEX (`account_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`cards` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`cards` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `card_number` VARCHAR(16) NOT NULL,
  `card_type` ENUM('debit', 'credit') NOT NULL,
  `expiry_date` DATE NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`card_number` ASC) VISIBLE,
  INDEX (`account_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`card_transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`card_transactions` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`card_transactions` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `card_id` BIGINT NOT NULL,
  `transaction_id` BIGINT NOT NULL,
  `merchant_name` VARCHAR(100) NOT NULL,
  `merchant_location` VARCHAR(255) NULL DEFAULT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `status` ENUM('pending', 'completed', 'failed') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`Id`),
  INDEX (`card_id` ASC) VISIBLE,
  INDEX (`transaction_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`card_id`)
    REFERENCES `banking_service`.`cards` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`transaction_id`)
    REFERENCES `banking_service`.`transactions` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`service_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`service_requests` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`service_requests` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `employee_id` BIGINT NULL,
  `request_type` ENUM('card replacement', 'loan inquiry', 'dispute', 'fraud report') NOT NULL,
  `status` ENUM('open', 'in progress', 'resolved') NOT NULL DEFAULT 'open',
  `created_at` DATETIME NOT NULL,
  `resolved_at` DATETIME NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX (`customer_id` ASC) VISIBLE,
  INDEX (`employee_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE SET NULL);


-- -----------------------------------------------------
-- Table `banking_service`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`appointments` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`appointments` (
  `Id` BIGINT NULL AUTO_INCREMENT,
  `service_request_id` BIGINT NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  `status` ENUM('scheduled', 'completed', 'canceled') NOT NULL DEFAULT 'scheduled',
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX (`service_request_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`service_request_id`)
    REFERENCES `banking_service`.`service_requests` (`Id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`audit_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`audit_logs` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`audit_logs` (
  `log_id` BIGINT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `employee_id` BIGINT NULL DEFAULT NULL,
  `action_type` ENUM('login', 'transaction', 'password change', 'loan approval') NOT NULL,
  `action_description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX (`user_id` ASC) VISIBLE,
  INDEX (`employee_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE SET NULL,
  CONSTRAINT ``
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE SET NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
