-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 05:45:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banking_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banking_service` ;

-- -----------------------------------------------------
-- Schema banking_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banking_service` ;
USE `banking_service` ;

-- -----------------------------------------------------
-- Table `banking_service`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`customers` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`customers` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_type` ENUM('INDIVIDUAL', 'COMPANY') NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `company_name` VARCHAR(100) NULL DEFAULT NULL,
  `tax_id` VARCHAR(20) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `industry` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`tax_id` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `banking_service`.`customer_representatives`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`customer_representatives` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`customer_representatives` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `is_primary_contact` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `fk_customer_representatives_customers1` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_representatives_customers1`
    FOREIGN KEY (`company_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`employees` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`employees` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `job_title` VARCHAR(50) NOT NULL,
  `hire_date` DATE NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `banking_service`.`employee_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`employee_roles` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`employee_roles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NULL,
  `role_name` VARCHAR(120) NOT NULL,
  `responsibilities` TEXT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_employee_roles_employees1` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_roles_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`branches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`branches` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`branches` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT NULL,
  `branch_name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `open_date` DATE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_branches_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_branches_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`accounts` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`accounts` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `account_type` ENUM('SAVINGS', 'CHECKING', 'BUSINESS') NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'EUR',
  `opened_date` DATETIME NOT NULL,
  `status` ENUM('ACTIVE', 'CLOSED', 'SUSPENDED') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`Id`),
  INDEX `fk_accounts_customers1` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`transactions` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`transactions` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `from_account_id` BIGINT NOT NULL,
  `to_account_id` BIGINT NOT NULL,
  `transaction_type` ENUM('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'PAYMENT', 'LOAN_REPAYMENT', 'CARD_PAYMENT') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('PENDING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (`Id`),
  INDEX `fk_transactions_accounts1` (`from_account_id` ASC) VISIBLE,
  INDEX `fk_transactions_accounts2` (`to_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_accounts1`
    FOREIGN KEY (`from_account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transactions_accounts2`
    FOREIGN KEY (`to_account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`loans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`loans` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`loans` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `loan_type` ENUM('PERSONAL', 'BUSINESS', 'MORTGAGE') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `interest_rate` DECIMAL(5,2) NOT NULL,
  `term_months` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `payment_date` DATE NOT NULL,
  `status` ENUM('ACTIVE', 'CLOSED', 'DEFAULTED') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`Id`),
  INDEX `fk_loans_accounts1` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_loans_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`deposits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`deposits` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`deposits` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `deposit_type` ENUM('FIXED', 'RECURRING') NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `interest_rate` DECIMAL(5,2) NOT NULL,
  `term_months` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `maturity_date` DATE NOT NULL,
  `status` ENUM('ACTIVE', 'CLOSED', 'WITHDRAWN') NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (`Id`),
  INDEX `fk_deposits_accounts1` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_deposits_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`cards` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`cards` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `account_id` BIGINT NOT NULL,
  `card_number` VARCHAR(16) NOT NULL,
  `card_type` ENUM('DEBIT_MASTERCARD', 'CREDIT_MASTERCARD', 'DEBIT_VISA', 'CREDIT_VISA') NOT NULL,
  `expiry_date` DATE NOT NULL,
  `cvv` VARCHAR(3) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX (`card_number` ASC) VISIBLE,
  INDEX `fk_cards_accounts1` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `banking_service`.`accounts` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`service_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`service_requests` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`service_requests` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `employee_id` BIGINT NULL,
  `request_type` ENUM('CARD_REPLACEMENT', 'LOAN_INQUIRY', 'DISPUTE', 'FRAUD_REPORT', 'OTHER') NOT NULL,
  `status` ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED') NOT NULL DEFAULT 'OPEN',
  `created_at` DATETIME NOT NULL,
  `resolved_at` DATETIME NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_service_requests_customers1` (`customer_id` ASC) VISIBLE,
  INDEX `fk_service_requests_employees1` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_requests_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_service_requests_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`appointments` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`appointments` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `service_request_id` BIGINT NOT NULL,
  `appointment_date` DATETIME NOT NULL,
  `status` ENUM('SCHEDULED', 'COMPLETED', 'CANCELED') NOT NULL DEFAULT 'SCHEDULED',
  `notes` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_appointments_service_requests1` (`service_request_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointments_service_requests1`
    FOREIGN KEY (`service_request_id`)
    REFERENCES `banking_service`.`service_requests` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`audit_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`audit_logs` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`audit_logs` (
  `log_id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `employee_id` BIGINT NULL DEFAULT NULL,
  `action_type` ENUM('LOGIN', 'TRANSACTION', 'PASSWORD_CHANGE', 'LOAN_APPROVAL') NOT NULL,
  `action_description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_audit_logs_customers1` (`customer_id` ASC) VISIBLE,
  INDEX `fk_audit_logs_employees1` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_audit_logs_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `banking_service`.`employees` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `banking_service`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking_service`.`addresses` ;

CREATE TABLE IF NOT EXISTS `banking_service`.`addresses` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `type` ENUM('CORRESPONDENCE', 'RESIDENCE') NOT NULL,
  `street` VARCHAR(245) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Address_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `banking_service`.`customers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
